# This is interestingly not set for us in the Cloud Function environment
GOOGLE_CLOUD_PROJECT: celo-mobile-mainnet
POSITION_IDS: 'curve,beefy,gooddollar,halofi,hedgey,locked-celo,mento,moola,stake-dao,ubeswap,uniswap,allbridge,aave'
SHORTCUT_IDS: 'gooddollar,hedgey,ubeswap'
GET_TOKENS_INFO_URL: 'https://blockchain-api-dot-celo-mobile-mainnet.appspot.com/tokensInfo'
EARN_SUPPORTED_NETWORK_IDS: 'arbitrum-one,celo-mainnet'
SIMULATE_TRANSACTIONS_URL: 'https://api.mainnet.valora.xyz/simulateTransactions'
