# This is interestingly not set for us in the Cloud Function environment
GOOGLE_CLOUD_PROJECT: celo-mobile-alfajores
POSITION_IDS: 'curve,gooddollar,halofi,hedgey,locked-celo,moola,ubeswap,uniswap'
SHORTCUT_IDS: 'gooddollar,hedgey,ubeswap'
