# This is interestingly not set for us in the Cloud Function environment
GOOGLE_CLOUD_PROJECT: celo-mobile-alfajores
POSITION_IDS: 'curve,gooddollar,halofi,hedgey,locked-celo,mento,moola,ubeswap,uniswap'
SHORTCUT_IDS: 'gooddollar,hedgey,ubeswap'
GET_TOKENS_INFO_URL: 'https://blockchain-api-dot-celo-mobile-alfajores.appspot.com/tokensInfo'
