name: Workflow

on:
  # Run on pushes to main..
  push:
    branches:
      - main
  # ..and any pull request.
  pull_request:

# Cancel any in progress run of the workflow for a given PR
# This avoids building outdated code
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-for-sh:
    name: Check for .sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "echo '*** Do not write .sh scripts! ***'; ! find . -type f -name '*.sh' | grep ."
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
      - run: yarn
      - run: yarn typecheck
      - run: yarn format:check
      - run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
      - run: yarn
      - run: yarn test:ci
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          path: coverage/lcov-report
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v3
  deploy-staging:
    name: Deploy staging
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          project_id: celo-mobile-alfajores
          credentials_json: ${{ secrets.ALFAJORES_SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'beta'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
      - run: yarn
      - run: yarn deploy:staging:http hooks-api
  deploy-production:
    name: Deploy production
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - test
      - deploy-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          project_id: celo-mobile-mainnet
          credentials_json: ${{ secrets.MAINNET_SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'beta'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
      - run: yarn
      - run: yarn deploy:production:http hooks-api
